From mathcomp Require Import ssreflect ssrbool ssrnat seq.
From LeanImport Require Import Lean.
From FoundationImported Require Import ImportedListSimple ImportedSubadditivity.
From FoundationCertificates Require Import
  PropSPropFoundation SubadditivityNatCorrespondence.
Require Import GeneratedListSimpleSource.

(** Canonical order- and multiplicity-preserving map from the MathComp
    sequence carrier to the exact monomorphic [List Nat] carrier generated by
    lean4export for the compiled Prosa.Util.List artifact. *)
Fixpoint list_simple_to_imported (xs : seq nat) :
    ImportedListSimple.List_inst1 Lean.Nat :=
  match xs with
  | [::] => ImportedListSimple.List_nil_inst1 Lean.Nat
  | x :: xs' => ImportedListSimple.List_cons_inst1 Lean.Nat
      (sub_nat_to_imported x) (list_simple_to_imported xs')
  end.

Lemma list_simple_foldl_nil {A B : Type} (f : A -> B -> A) (z : A) :
  Lean.eq
    (ImportedListSimple.List_foldl_inst3 A B f z
      (ImportedListSimple.List_nil_inst1 B)) z.
Proof. exact (@Lean.eq_refl A z). Qed.

Lemma list_simple_foldl_cons {A B : Type} (f : A -> B -> A)
    (z : A) (x : B) (xs : ImportedListSimple.List_inst1 B) :
  Lean.eq
    (ImportedListSimple.List_foldl_inst3 A B f z
      (ImportedListSimple.List_cons_inst1 B x xs))
    (ImportedListSimple.List_foldl_inst3 A B f (f z x) xs).
Proof. exact (@Lean.eq_refl A
  (ImportedListSimple.List_foldl_inst3 A B f (f z x) xs)). Qed.

Lemma list_simple_headD_nil {A : Type} (z : A) :
  Lean.eq
    (ImportedListSimple.List_headD_inst1 A
      (ImportedListSimple.List_nil_inst1 A) z) z.
Proof. exact (@Lean.eq_refl A z). Qed.

Lemma list_simple_headD_cons {A : Type} (z x : A)
    (xs : ImportedListSimple.List_inst1 A) :
  Lean.eq
    (ImportedListSimple.List_headD_inst1 A
      (ImportedListSimple.List_cons_inst1 A x xs) z) x.
Proof. exact (@Lean.eq_refl A x). Qed.

Lemma list_simple_getLastD_nil {A : Type} (z : A) :
  Lean.eq
    (ImportedListSimple.List_getLastD_inst1 A
      (ImportedListSimple.List_nil_inst1 A) z) z.
Proof. exact (@Lean.eq_refl A z). Qed.

Lemma list_simple_getLastD_singleton {A : Type} (z x : A) :
  Lean.eq
    (ImportedListSimple.List_getLastD_inst1 A
      (ImportedListSimple.List_cons_inst1 A x
        (ImportedListSimple.List_nil_inst1 A)) z) x.
Proof. exact (@Lean.eq_refl A x). Qed.

Lemma list_simple_getLastD_cons_cons {A : Type} (z x y : A)
    (xs : ImportedListSimple.List_inst1 A) :
  Lean.eq
    (ImportedListSimple.List_getLastD_inst1 A
      (ImportedListSimple.List_cons_inst1 A x
        (ImportedListSimple.List_cons_inst1 A y xs)) z)
    (ImportedListSimple.List_getLastD_inst1 A
      (ImportedListSimple.List_cons_inst1 A y xs) z).
Proof. exact (@Lean.eq_refl A
  (ImportedListSimple.List_getLastD_inst1 A
    (ImportedListSimple.List_cons_inst1 A y xs) z)). Qed.

Definition list_simple_target_max (a b : Lean.Nat) : Lean.Nat :=
  ImportedListSimple.Nat_max a b.

Definition list_simple_imported_false_elim (Q : SProp)
    (H : ImportedListSimple.False) : Q := match H return Q with end.

Definition list_simple_imported_false_to_strict
    (H : ImportedListSimple.False) : StrictlyInhabited Logic.False :=
  match H with end.

Lemma list_simple_max_canonical (a b : nat) :
  Lean.eq
    (list_simple_target_max (sub_nat_to_imported a) (sub_nat_to_imported b))
    (sub_nat_to_imported (maxn a b)).
Proof.
  unfold list_simple_target_max, ImportedListSimple.Nat_max,
    ImportedListSimple.Max_max_inst1, ImportedListSimple.Nat_instMax,
    ImportedListSimple.maxOfLe_inst1.
  cbn.
  destruct (ImportedListSimple.Nat_decLe
    (sub_nat_to_imported a) (sub_nat_to_imported b)) as [Hnle|Hle].
  - have Hrel := sub_nat_le_correspondence a (sub_nat_to_imported a)
      b (sub_nat_to_imported b) (sub_nat_rel_canonical a)
      (sub_nat_rel_canonical b).
    have Hnot : ~ is_true (leq a b).
    { intro Hab.
      exact (interpret_strict Logic.False
        (list_simple_imported_false_to_strict
          (Hnle (prop_to_sprop _ _ Hrel Hab)))). }
    have Hba : is_true (leq b a).
    { move: (leq_total a b) => /orP [Hab|Hba]; last exact Hba.
      exfalso. exact (Hnot Hab). }
    have Hmax : maxn a b = a := (elimT maxn_idPl Hba).
    rewrite Hmax.
    exact (@Lean.eq_refl Lean.Nat (sub_nat_to_imported a)).
  - have Hab : is_true (leq a b).
    { have Hrel := sub_nat_le_correspondence a (sub_nat_to_imported a)
        b (sub_nat_to_imported b) (sub_nat_rel_canonical a)
        (sub_nat_rel_canonical b).
      exact (sprop_to_prop _ _ Hrel Hle). }
    have Hmax : maxn a b = b := (elimT maxn_idPr Hab).
    rewrite Hmax.
    exact (@Lean.eq_refl Lean.Nat (sub_nat_to_imported b)).
Qed.

Lemma list_simple_foldl_max_canonical (z : nat) (xs : seq nat) :
  Lean.eq
    (ImportedListSimple.List_foldl_inst3 Lean.Nat Lean.Nat
      ImportedListSimple.Nat_max (sub_nat_to_imported z)
      (list_simple_to_imported xs))
    (sub_nat_to_imported (foldl maxn z xs)).
Proof.
  revert z. induction xs as [|x xs IH]; intro z.
  - exact (list_simple_foldl_nil ImportedListSimple.Nat_max
      (sub_nat_to_imported z)).
  - refine (sub_imported_eq_trans _ _ _
      (list_simple_foldl_cons ImportedListSimple.Nat_max
        (sub_nat_to_imported z) (sub_nat_to_imported x)
        (list_simple_to_imported xs)) _).
    refine (sub_imported_eq_trans _ _ _
      (sub_imported_eq_congr
        (fun init => ImportedListSimple.List_foldl_inst3
          Lean.Nat Lean.Nat ImportedListSimple.Nat_max init
          (list_simple_to_imported xs)) _ _
        (list_simple_max_canonical z x)) _).
    exact (IH (maxn z x)).
Qed.

Theorem max0_definition_certificate (xs : seq nat) :
  Lean.eq
    (ImportedListSimple.Prosa_Util_List_max0
      (list_simple_to_imported xs))
    (sub_nat_to_imported (GeneratedListSimpleSource.max0 xs)).
Proof. exact (list_simple_foldl_max_canonical 0 xs). Qed.

Theorem first0_definition_certificate (xs : seq nat) :
  Lean.eq
    (ImportedListSimple.Prosa_Util_List_first0
      (list_simple_to_imported xs))
    (sub_nat_to_imported (GeneratedListSimpleSource.first0 xs)).
Proof.
  destruct xs as [|x xs].
  - exact (@Lean.eq_refl Lean.Nat Lean.Nat_zero).
  - exact (@Lean.eq_refl Lean.Nat (sub_nat_to_imported x)).
Qed.

Theorem last0_definition_certificate (xs : seq nat) :
  Lean.eq
    (ImportedListSimple.Prosa_Util_List_last0
      (list_simple_to_imported xs))
    (sub_nat_to_imported (GeneratedListSimpleSource.last0 xs)).
Proof.
  induction xs as [|x xs IH].
  - exact (@Lean.eq_refl Lean.Nat Lean.Nat_zero).
  - destruct xs as [|y ys].
    + exact (@Lean.eq_refl Lean.Nat (sub_nat_to_imported x)).
    + refine (sub_imported_eq_trans _ _ _
        (list_simple_getLastD_cons_cons Lean.Nat_zero
          (sub_nat_to_imported x) (sub_nat_to_imported y)
          (list_simple_to_imported ys)) _).
      exact IH.
Qed.
